### ISSUE TITLE
HOW TO AUTHENTICATE

### ISSUE THREAD

**Issue by RhythmicGaming** [OpenVoiceOS/skill-ovos-spotify#1]
trying to run auth.py to set up my app id but i keep getting 'premission denied' when running as default user. when I run as sudo i get a traceback 'syntax error near unexpected token'('
and 'AUTH_DIR = os.environment.ger('SPOTIFY_SKILLS_DIR'

for line 23

**Comment by forslund** [comment]
I tried to replicate but couldn't. Can you provide the exact command line you used?

I did run into some issues with installing and will clean up some rough edges and update the readme.

**Comment by forslund** [comment]
Closing since this has been completely changed now and is relying on the ovos oauth database
